# Tomcat配置
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 10
    max-connections: 5000
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true


# 支付宝参数
alipay:
  # 回调地址
  notify-url: http://5r32hpu.hn3.mofasuidao.cn/alipay/callBack
  # 支付宝网关名、partnerId和appId
  open-api-domain: https://openapi.alipaydev.com/gateway.do
  mcloud-api-domain: http://mcloudmonitor.com/gateway.do
  pid: 2088102175076636
  appid: 2016091100483133
  # RSA私钥、公钥和支付宝公钥
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2se6cG0q/y2Os96fitezdglInNhEonfXdGD3AM5c49OKpQ1vFgVNXIHFiRO4U3kquqdVPTWXGtMU7DVFBFQDcAsIjvMu9LAYi8Dn6VaFXESiebMbYQGdiq1E9oSFo5PaxSaOXyG9D336SQc+HBssmFkkDi/sQrzW1XboWesBboxMcJbqJzHOGwBGxuI9pnPmfLE5MPqIkJZ07rauEOAiPziugO7cuC4D5f4xF4eJl36p/z4aX4GRFRLA2GczDZ3nvM03yfaH9v7yKXKI8D5I3pZ8OM421DigPY1fHTSDIojfizSprmpXF8QN2zLNmmUfQ3qIKrJDfUEORXB4Os9ptAgMBAAECggEAHwBoniLfd1ZbLrHD0mvOqvP/XtoE5WCQpRkE+YWHpsmfYNumSgidDM7bjrJluDLUd3koUlGu8J4iTdf/rsySncL2ELxr0kkTLYCYRgub2jt2KhQJVg7vvEWX/p5GHhekaQc29H21q83UG5uBTMdxV6A2eZyaWQVyVrl153SjCamD0Rf4UXFLR6ZXdHY0E0/D/Rikndd/ps2XCR3pbCBa5BqR65ipE6/tifW9BO2HP1tDohyi6wCbRdxNH7Qsn5by9Q5hAKEt8cO/5pmpn+WhfQLXhkot8HIhC+c46IkJtCmIOHGBoLkvltE4uvzMVwH8iLuMUsV4AB9Wqx+j/DHLgQKBgQDtSz2DnBbL4Swgw5J5ubSKDK4TIFIqoYzUyexQpmxE4+XLnRZ6KsJhc6NvgLOzfuIDbpUS8RtZ27M9L+2rja/HDXQR4qnyUsoxaSBShWBCmxBISKQvtL42lboXfBeVR+KwnUB9P1LWEmyFqwyZ0NO6gyKxguSsMKHP6Qu/Nol3TQKBgQDFGNkUzdwI59BRo8fUmWAhYM1sxHiq1jK32qImriaTb2D5RbpAS+9jS3+8TZq9PA8lzdgQ0GB8L+Qc3KlNY8Q1cskEPUNi/biqIQnY8Wy6zHq3UAGVsa0Rofwx3brGwCNygjZUINIijAU6Fzgdu6d/wGpbbPfHdPybm9SLyEOfoQKBgQDiHdpmOSz35n/YUMSZPb6t9dtC2n+xo/PBKREI4S02kDv/RJeQnoJPvpO0wt16Y6QXRR7EyAAaJmKsIanG2eLwOP+rs2PiR8XoQ5bLS9EoZv6jAqWB2CeReCe2DUejtrZrOc2kC91xpGjJDu+Y+wdnKWK76FDjTAxFRHsvIFbp2QKBgDHP1NUoLcrmY0SuwssdNClbYK9zfBeY6NqEW+SwsLkkNfrpv2eOiWKr6w15A3l920ovmsKtFyVrqRgOQI95flYPu3Ph080J2IjOrsFwSo1vLjhz9OKTM+035hfoNNMULiE7fWWHofPvNUb4JUuGaI+l3ntar8ht7YWaPX5ST5zhAoGAEA37KhJ2BwD6e7SVUHuHj+SUySqIvjAfQJ7BnCoUzkBISOr9i4PxDNuYiHOKJSSns09G2moi9jILVRXrgGG8upuQqFT13/RI0SLBOnfufgy/MupQdyoNT/IxlaNF/twCu6ZdQW+Dt78UuhkP8Skgvua5f+qDd+aQJXBP3EKGMJM=
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrHunBtKv8tjrPen4rXs3YJSJzYRKJ313Rg9wDOXOPTiqUNbxYFTVyBxYkTuFN5KrqnVT01lxrTFOw1RQRUA3ALCI7zLvSwGIvA5+lWhVxEonmzG2EBnYqtRPaEhaOT2sUmjl8hvQ99+kkHPhwbLJhZJA4v7EK81tV26FnrAW6MTHCW6icxzhsARsbiPaZz5nyxOTD6iJCWdO62rhDgIj84roDu3LguA+X+MReHiZd+qf8+Gl+BkRUSwNhnMw2d57zNN8n2h/b+8ilyiPA+SN6WfDjONtQ4oD2NXx00gyKI34s0qa5qVxfEDdsyzZplH0N6iCqyQ31BDkVweDrPabQIDAQAB
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo9yFK7eFyCpxgjhdf8TnkptAk81O2Xv1DfJOjwKlufViB2MyKX6EbBXt3fs0BZzomnKv49cRo/cxbFc4PCFmFKIxLjXq8xDVWTba3/Ui6gf2Gw0ZXlHyFCZ1AKOkAYB0OV3uYe9RYYEvHo2EKvCHhm7XdVuMS5WT4CAcdWv6gt6Wo4/gE0vtcKA9kjQUHVoSi8RFsVUJda75x9zKEnAZGA1fqIa0b+1+6C83RHUVMw73nZYIGKWLaxhhaDvAJIY0Ecgi1UaS1nfO0zbq/w91HHzL1ZitaqSd8ze8dO5RZpJYGnoJow4ciPazXR0MxgubN2iVGfWXX+TvruRy4ZGf2QIDAQAB
  # 签名类型: RSA->SHA1withRsa,RSA2->SHA256withRsa
  sign-type: RSA2
  # 当面付最大查询次数和查询间隔（毫秒）
  max-query-retry: 5
  query-duration: 5000
  # 当面付最大撤销次数和撤销间隔（毫秒）
  max-cancel-retry: 3
  cancel-duration: 2000
  # 交易保障线程第一次调度延迟和调度间隔（秒）
  heartbeat-delay: 5
  heartbeat-duration: 900

# 日志相关
logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.pay: debug
    com.github.binarywang.wxpay: debug

# 微信支付参数
wx:
  pay:
    appId: #微信公众号或者小程序等的appid
    mchId: #微信支付商户号
    mchKey: #微信支付商户密钥
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
