
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

spring:
#ehcache
  cache:
    type: ehcache
  ehcache:
  config: classpath:ehcache.xml
  #mysql
  datasource:
    url: jdbc:mysql://129.204.236.147:3306/eshop
    username: root
    password: qinxue420923
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
# redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1




# MyBatis
mybatis:
  typeAliasesPackage: com.github.cache
  mapperLocations: classpath:mybatis/mapper/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml


logging:
  level:
    org.springframework: INFO