server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

spring:
#ehcache
  cache:
    type: ehcache
  ehcache:
  config: classpath:ehcache.xml
#mysql
  datasource:
    url: jdbc:mysql://129.204.236.147:3306/eshop
    username: root
    password: qinxue420923
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
# redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1
# kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9092 #broker地址
    #生产者配置
    listener:
      ack-mode: manual  #开启手动 ack
    producer:
      batch-size: 16 # 缓存的大小
      retries: 0 #发送失败重试次数
      buffer-memory: 33554432  #控制生产者可用的缓存总量
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: "all"     #指定了all将会阻塞消息，这种设置性能最低，但是是最可靠的。
    #消费者配置
    consumer:
      auto-offset-reset: latest  #可选的值为latest, earliest, none
      enable-auto-commit: false  #是否自动提交
#      auto-commit-interva: 100  #消费者偏移自动提交给Kafka的频率（以毫秒为单位
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-consumer-group  #消费组

# MyBatis
mybatis:
  typeAliasesPackage: com.github.cache
  mapperLocations: classpath:mybatis/mapper/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

# zk
zookeeper:
  address: 127.0.0.1:2181
  timeout: 400

logging:
  level:
    org.springframework: INFO